### ISSUE TITLE
Add new functionality for the fields

### ISSUE THREAD

**Issue by marioCluml** [aicers/review-web#118]
Add:
- [ ] : `remove_single_node` for removing single node when pressing revert 
- [ ] : `revert_node` for reverting the node to the previous values 
- [ ] : `insert_draft_node` for updating draft node for `in_progress`

**Comment by sophie-cluml** [comment]
이 이슈의 내용은 https://github.com/aicers/review-web/issues/127 에서 변경되어 적용되었습니다. 이 이슈는 더 이상 유효하지 않으므로 close 합니다
