### ISSUE TITLE
Request for release update of review-web to support review-database v0.24

### ISSUE THREAD

**Issue by msk** [aicers/review-web#124]
It is vital for our users to upgrade to a REview version based on review-database v0.24 before proceeding to versions tied to review-database 0.25 or later. This step is mandatory due to the migration features being introduced in v0.25.0, which are essential for users moving from the schema used by v0.24.

To facilitate this, we have prepared PR #120, designed to adapt to the API changes in review-database v0.24. However, it’s important to note that this PR may require additional modifications. We are currently awaiting feedback on https://github.com/petabi/review-database/issues/171#issuecomment-1896648319, which could influence further adjustments to ensure full compatibility and functionality.

Given this context, we request the following:

1. Review and conditional merge of PR #120. We will make any adjustment that may be needed based on the discussion in petabi/review-database#171.
2. Release of a new review-web version based on review-database v0.24. This critical update will enable our users to upgrade their setups in preparation for the changes introduced in the forthcoming review-database v0.25 and beyond.

**Comment by minshao** [comment]
@sehkone  could you tag it as well? thanks~

**Comment by sehkone** [comment]
> @sehkone could you tag it as well? thanks~

@minshao 
I just did. I was in the middle of doing something else. ( • ᴗ - )

**Comment by minshao** [comment]
@sehkone When you have time, could you re-tag it on the tip of main (commit id: 19ed5c53d)? 
Thank you so much~~~ 0(^ - ^)0~~~

* To delete the tag: click the following [0.18.0](https://github.com/aicers/review-web/releases/tag/0.18.0) and you should be able to find a delete button at the right corner of the page.
* Then delete local tag with `git tag -d 0.18.0`
* Checkout main and make sure it's at 19ed5c53d
* Tag with: `git tag 0.18.0 -a -m "Release 0.18.0"`
* Then push the tag as usual

**Comment by sehkone** [comment]
> @sehkone When you have time, could you re-tag it on the tip of main (commit id: [19ed5c5](https://github.com/aicers/review-web/commit/19ed5c53d72c54365d9ba5127d8d13ae564f4c06))? Thank you so much~~~ 0(^ - ^)0~~~
> 
> * To delete the tag: click the following [0.18.0](https://github.com/aicers/review-web/releases/tag/0.18.0) and you should be able to find a delete button at the right corner of the page.
> * Then delete local tag with `git tag -d 0.18.0`
> * Checkout main and make sure it's at [19ed5c5](https://github.com/aicers/review-web/commit/19ed5c53d72c54365d9ba5127d8d13ae564f4c06)
> * Tag with: `git tag 0.18.0 -a -m "Release 0.18.0"`
> * Then push the tag as usual

@minshao 
I had made an error the first time around, so I had fixed it like you said and added the above mention.

**Comment by minshao** [comment]
It happens~~ I've updated my PR in review accordingly. Thanks for the help! \( ^ - ^ )/
