### ISSUE TITLE
Add `get_config` and `set_config` methods to `AgentManager`

### ISSUE THREAD

**Issue by msk** [aicers/review-web#160]
As part of our ongoing efforts to refactor `review-web` for better encapsulation and abstraction, we've identified a need to add specific methods to the `AgentManager` trait that abstract away the internal communication protocol details (See #144). This issue addresses the addition of `get_config` and `set_config` methods to support module configuration in a way that aligns with our encapsulation goals.

Proposed by @sophie-cluml (https://github.com/aicers/review-web/pull/148#discussion_r1517068147)

**Comment by sophie-cluml** [comment]
For the question in the comment of #148, I suggest below.
```rust
async fn get_config(&self, hostname: &str, agent_key: &str) -> Result<oinq::Config, anyhow::Error>
async fn set_config(&self, hostname: &str, agent_key: &str, config: &oinq::Config) -> Result<(), anyhow::Error>
```

For `agent_key`, I think it's also possible to define an enum, like below, and use the type instead of `&str`. 
```rust
enum AgentKey {
  piglet,
  crusher,
  hog,
  ...
}
```
