### ISSUE TITLE
Refactor `applyNode` Mutation to Use `AgentManager::set_config`

### ISSUE THREAD

**Issue by msk** [aicers/review-web#191]
In alignment with our ongoing efforts to enhance encapsulation and abstraction, we have introduced specific functions to the `AgentManager` trait (#144). These functions are designed to abstract away the internal communication details with agents. One such function, `AgentManager::set_config`, has been added but is not currently utilized by the `applyNode` GraphQL mutation. The current implementation of the `applyNode` mutation directly constructs and sends a message to the agent, bypassing the `AgentManager`'s abstraction. This approach violates the encapsulation principle by exposing the mutation to the specifics of the agent communication protocol.

This issue proposes a refactor of the `applyNode` mutation to leverage the `AgentManager::set_config` method, moving away from directly creating and sending messages.

**Comment by sophie-cluml** [comment]
We also need to refactor `nodeShutdown` GraphQL API. Let me handle that too.
