### ISSUE TITLE
Fix overflow at `nodeStatusList` API

### ISSUE THREAD

**Issue by sophie-cluml** [aicers/review-web#208]
https://github.com/aicers/review-web/issues/37 와 관련하여 `NodeStatus` 쪽 부분에 한정하여 개선을 하고자 합니다. To fix it, GraphQL API should return these fields as wrapped as StringNumber.

```
total_memory
used_memory
total_disk_space
used_disk_space
ping
```

https://github.com/aicers/review-web/blob/d808245a7c03e4bbba2b6c065965ad1e780b4189/src/graphql/node.rs#L405-L428

**Comment by sehkone** [comment]
1. Regarding precision loss, would not returning String avoid it?
2. What exactly "overflow" means? 

I think our APIs should keep the attributes of the values as much as possible. Returning `String` should be a last resort.

**Comment by sophie-cluml** [comment]
Good, what do you think about `StringNumber` instead?
https://docs.rs/async-graphql/latest/async_graphql/types/struct.StringNumber.html#

**Comment by sehkone** [comment]
As we discussed offline, the type we are concerned with is only `u64`, which GraphQL's standard types cannot represent.

**Comment by sophie-cluml** [comment]
Agreed, and not a big deal, just a quick comment, that there is `i64` as well, which will be handled as `StringNumber`, just like `u64`.
