### ISSUE TITLE
Remove the redundant fields and change the types in `NodeSettings`

### ISSUE THREAD

**Issue by sehkone** [aicers/review-web#224]
`NodeSettings` currently includes `protocols`, `protocol_list`, `sensors`, and `sensor_list` for the analysis engine. When the engine queries the data lake storing raw events from sensors, it might need to filter events by specific protocols or sensors. The `protocol_list` specifies which protocols the engine will analyze, and the `sensor_list` specifies which sensors' events the engine will analyze. `protocols` and `sensors` seem to indicate whether the engine should use these criteria. However, `protocols` and `sensors` become unnecessary if we change `protocol_list` and `sensor_list` to `Option`. When `protocol_list` is `None`, the engine will analyze all events without filtering by protocols, and the same approach applies to `sensor_list`.

Additionally, I suggest changing `protocol_list` and `sensor_list` to `Option<Vec<String>>` instead of `Option<HashMap<String, bool>>`. We don't need to track protocols and sensors set to false because the engine only needs to know which ones to include when filtering events in the data lake. This also allows for the addition of more protocols and sensors in the future.

Since `protocols` and `sensors` are simpler names, I recommend using these names instead of `protocol_list` and `sensor_list` with the type `Option<Vec<String>>`. The elements should be sorted in alphabetical order.

**Comment by sophie-cluml** [comment]
@sehkone, given that we removed the redundant fields and changed `[protocol|sensor]_list` to `[protocol|sensor]s`, the analysis engine will behave like below. 

- When `[protocol|sensor]s` is `None`, the analysis engine will use its default protocols and sensors for filtering.
- When `[protocol|sensor]s` is `Some` with an empty vector, the analysis engine will use no protocols and no sensors for filtering.

This is slightly different from what you mentioned:

> When protocol_list is None, the engine will analyze all events without filtering by protocols, and the same approach applies to sensor_list.

Can you check please?

**Comment by syncpark** [comment]
> When `protocol_list` is `None`, the engine will analyze all events without filtering by protocols, and the same approach applies to `sensor_list`.

If the `protocol_list` and `sensor_list` are options to be used in `semi-supervised model analyzing engine`, `None` value for the options must be implemented to get `NO` events from the sensors instead of `ALL` events. The engine should run with all events from data lake when the value of `protocol_list` option is set to `all`.

Because sometimes the `semi-supervised model analyzing engine` run as standalone mode to monitor or mange the node where the agent is not required to be installed.

**Comment by sehkone** [comment]
When `protocols` is `None`, the engine queries the data lake for all events without filtering by protocols. This means it will retrieve all events regardless of their protocols. On the other hand, when `protocols` is `Some` but empty, the engine queries the data lake with a filter that matches no protocols, meaning it will retrieve no events.

**Comment by sophie-cluml** [comment]
@sehkone 마지막에 써주신 아래 제약조건은

> The elements should be sorted in alphabetical order.

GraphQL API 의 input 또는 response에서도 꼭 필요한 것은 아니고, review-database에 데이터를 저장하거나 꺼내올 때에도 필요한 제약은 아니고, 이 세팅값을 사용하는 모듈 입장에서도 순서가 필요하지 않아서, 이 제약조건이 없어도 될 것 같다고 생각이 듭니다. 이 ordering 은 고려하지 않아도 되지 않을까 싶은데 의견 알려주실 수 있을까요?

순서가 알파벳 순서이면 좋다인지 그 순서여야만 한다(should)인지 정도만 싱크를 맞출 수 있어도 좋을 것 같습니다. 만약 그 후자라면, review-database에서 기존의 데이터를 마이그레이션 할 때에 그 순서대로 마이그레이션을 강제하는 코드도 넣어야 하는 제약이 생기기 때문에 그 부분이 궁금하여 질문드립니다.

**Comment by sehkone** [comment]
@sophie-cluml If we were confident that we would never compare two values to see if they are the same, we would not need to order the elements of a vector. However, since we cannot exclude the possibility that this might be necessary later, I think our approach should be to include the ordering.
