### ISSUE TITLE
Remove the data lake's configuration in `NodeSettings` and create `GigantoSettings`

### ISSUE THREAD

**Issue by sehkone** [aicers/review-web#227]
Since the data lake operates independently, we don't need to store its settings on the central server. However, we do need to store a user's draft for all modules.

Given this change, I suggest we remove all fields regarding the data lake in `NodeSettings`, except for the boolean `giganto` field indicating whether the data lake is supposed to run or not. Additionally, we should create another data structure, `GigantoSettings`, and add a new field, `giganto_settings_draft`, to `Node` to store the user's input for the data lake's settings.

**Comment by BLYKIM** [comment]
pending: review-database 수정 이후 다시 진행할 예정입니다.

**Comment by BLYKIM** [comment]
설정값에 대한 설계 방식이 변경되어 #249 PR과 함께 Close되도록 합니다.

**Comment by sophie-cluml** [comment]
@BLYKIM 설계 방식이 달라져서 이 이슈의 내용이 해당 PR에서의 구현 방향과 다르므로, 이 이슈를 obsolete한 것으로 보아 수동으로 close 하는게 나을 것 같다고 생각합니다. 동시에 to-do list에서도 제거하는 것이 맞다고 생각이 들어요.

**Comment by BLYKIM** [comment]
to-do list에서 제거하였습니다. Issue close합니다.
