### ISSUE TITLE
Improve flexibility of fields related to sensors in `NodeSettings`

### ISSUE THREAD

**Issue by sophie-cluml** [aicers/review-web#228]
`NodeSettings` has below fields to represent some of sensor's configurations.

```rust
    http: bool,
    office: bool,
    exe: bool,
    pdf: bool,
    html: bool,
    txt: bool,
```

There are two problems with current implementation. 
- These are all `bool` in type, which means whenever we want to modify the sensor's configurations, we need to modify review-web.  
- These fields look like they are independent configurations, but there is dependency and hierarchy. , `office`, `exe`, `pdf`, `html`, `txt` belong to `http`.

I suggest to change the above fields like below:

```rust
  // this can currently have `office`, `exe`, `pdf`, `html`, `txt`, but more can be added in the future
  http_extract_options: Option<Vec<String>>,  
```

This is how the values are represented currently and afterwards:
| CURRENT | AFTERWARDS | 
| -- | -- |
| http: false, office: false, exe: false, pdf: false, html: false, txt: false | http_extract_options: None |
| http: true, office: false, exe: false, pdf: false, html: false, txt: false | http_extract_options: Some of empty vector | 
| http: true, office: true, exe: true, pdf: false, html: false, txt: false | http_extract_options: Some of vector, having "office" and "exe" as elements |

**Comment by syncpark** [comment]
@sophie-cluml 
It looks ok to me. The new version of `NodeSettings` is better to reflect the functionality.

**Comment by sophie-cluml** [comment]
https://github.com/petabi/review-database/issues/283 에서의 디스커션에 따라서 이 이슈를 닫습니다.
