### ISSUE TITLE
Must specify number types in documentation comment when using `StringNumber` in GraphQL API responses

### ISSUE THREAD

**Issue by sophie-cluml** [aicers/review-web#231]
### Background

Recently, https://github.com/aicers/review-web/issues/208 changed the `totalMemory`, `usedMemory`, `totalDiskSpace`, `usedDiskSpace`, `ping` to `StringNumber`.

The GraphQL schema in SDL format we get looks like below. This means the information of `StringNumber`'s number type is lost. This happened even though we specified the types of `totalMemory`, `usedMemory`, `totalDiskSpace`, `usedDiskSpace`, `ping` as `StringNumber<u64>`, `StringNumber<u64>`, `StringNumber<u64>`, `StringNumber<u64>`, `StringNumber<i64>`, respectively.

```graphql
type NodeStatus {
  # The hostname of the node.
  name: String!

  # The average CPU usage in percent.
  cpuUsage: Float

  # Whether review is online or not.
  review: Boolean

  # Whether piglet is online or not.
  piglet: Boolean

  # actual piglet configuration
  pigletConfig: PigletConfig

  # Whether reconverge is online or not.
  reconverge: Boolean

  # actual reconverge configuration
  reconvergeConfig: ReconvergeConfig

  # Whether hog is online or not.
  hog: Boolean

  # actual hog configuration
  hogConfig: HogConfig
  id: ID!
  totalMemory: StringNumber
  usedMemory: StringNumber
  totalDiskSpace: StringNumber
  usedDiskSpace: StringNumber
  ping: StringNumber
}

scalar StringNumber
```

This calls for the need to correctly specify the number types of the fields that are represented as `StringNumber`, so that the client side of this GraphQL API can appropriately know into which number type it can parse the fields.

### Tasks
1. Specify the number types of above 5 fields in documentation comment.
2. Be aware that we should ensure we specify the number types when using `StringNumber`.

**Comment by sehkone** [comment]
@sophie-cluml 
Rustdoc is a tool run by `cargo doc` that generates HTML documentation from code comments in the `target/doc` directory. I believe the async-graphql library uses comments in the code to generate the GraphQL playground. Although it might use the rustdoc tool internally, I think it would be clearer to mention just "Rust comments," not "rustdoc" itself, to imply that we should provide detailed descriptions through the GraphQL playground.

**Comment by sophie-cluml** [comment]
@sehkone Thank you for the info. I found that it is called "Documentation comment", so let me use the term. https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html?highlight=rustdoc#making-useful-documentation-comments

**Comment by sophie-cluml** [comment]
Also, you are right about this part:

> I believe the async-graphql library uses comments in the code to generate the GraphQL playground.

So, what I think we need is to specify the number type to the existing documentation comment.
