### ISSUE TITLE
`Internal network list`를 처리 할 수 있는 Graphql api 구현 

### ISSUE THREAD

**Issue by kimhanbeom** [aicers/review-web#24]
관련 이슈: https://github.com/aicers/hog/issues/388
선행 이슈: https://github.com/petabi/review-database/issues/65

web에서 `internal network list`에 대해 목록 보기/추가/수정/삭제 를 할 수 있도록 4가지의 Graphql API를 구현합니다.

**Comment by sehkone** [comment]
이미 구현이 되어 있습니다.

<img width="1087" alt="Screenshot 2023-05-19 at 8 06 02 AM" src="https://github.com/aicers/review-web/assets/55010932/c8f7ec8d-e97d-4cd9-8652-e7a66322d893">

**Comment by sehkone** [comment]
@kimhanbeom 확인하고 현재 있는 API로 충분하면 이 이슈를 닫아 주세요.

**Comment by kimhanbeom** [comment]
필요한 기능이 전부 있어 close 합니다.
