### ISSUE TITLE
Create a new GraphQL API that provides default configuration values of agents

### ISSUE THREAD

**Issue by sophie-cluml** [aicers/review-web#246]
We are moving toward the direction of providing full configuration to agents from central management server. While doing so, there are some configuration items that have default values.  So we want to open a new API, where API clients can fetch the default values.

We need to define the default values in code, and create the new API.

**Comment by sehkone** [comment]
@sophie-cluml 
I don't think this is the best approach. It would be better for the review-web to be independent of the specific configuration of agents. This means that any default values should be provided by the UI.

**Comment by sehkone** [comment]
Since we decided to adopt the full configuration in the format of TOML strings, only two endpoint subjects, the UI and the agents, are now able to read and write configurations.

**Comment by sophie-cluml** [comment]
That sounds right, let me close this issue!
