### ISSUE TITLE
Update `applyNode` API behavior

### ISSUE THREAD

**Issue by sophie-cluml** [aicers/review-web#251]
### Background
https://github.com/aicers/review-web/issues/245 작업 이후, `profile`, `profile_draft`, `giganto`, `agents`, `config`, `draft` 와 같은 필드를 review-web에서도 사용할 수 있습니다.

### Tasks
- When there is an update in the configuration of a node after users click the apply button, central management server notifies the corresponding agents of the changes. We can use review-protocol crate's interface to notify the agents. At the same time, central management server updates the node's data, such as `name` with `name_draft`, `profile` with `profile_draft` ~and sets `profile_draft` to `None`~, and updates `config` with `draft`. ~For Giganto, `draft` will be set to `None`.~
- We need to log apply actions along with the `profile`, `profile_draft`, `config`, `draft` and the timestamp.

**Comment by sehkone** [comment]
> * When there is an update in the configuration of a node after users click the apply button, central management server notifies the corresponding agents of the changes. We can use review-protocol crate's interface to notify the agents. At the same time, central management server updates the node's data, such as `name` with `name_draft`, `profile` with `profile_draft` and sets `profile_draft` to `None`, and updates `config` with `draft`. For Giganto, `draft` will be set to `None`.

I don't think `profile_draft` needs to be set to `None` as `draft` remains unchanged.

**Comment by sophie-cluml** [comment]
@sehkone 같은 맥락에서 giganto의 `draft` 도 `None` 으로 세팅할 필요가 없을 것 같아서 맨 위 본문에서 해당 내용도 cross out 처리하였습니다.
