### ISSUE TITLE
Add new APIs to get and update user's language setting

### ISSUE THREAD

**Issue by div-seungha** [aicers/review-web#268]
This issue was created to support changes caused by the following issue: https://github.com/petabi/review-database/issues/308
- Add two new APIs in review-web: one for retrieving the user's language setting, and another for updating it.

**Comment by sophie-cluml** [comment]
I saw this https://github.com/aicers/review-web/pull/258#issuecomment-2297737521
> (but I may have misunderstood the meaning of the word 'retrieve'. I understood the word in the meaning of 'recovery.' If so, please let me know with comments here.)

And, for that question, I believe "retrieve" means "get" or "fetch". Or "Read" in CRUD (Create, Read, Update, Delete), if this sounds more familiar to you. So I think it is beneficial to include "retrieve" or any word that could convey the meaning in the title of this issue.
