### ISSUE TITLE
Removal of functions not mentioned in CHANGELOG

### ISSUE THREAD

**Issue by msk** [aicers/review-web#271]
@petabi is developing an application that relies on the `review-web` crate. Previously, our application used the `get_node_settings` and `get_customer_id_of_review_host` functions, but after updating to commit `6d756238`, we encountered compilation errors because these functions appear to have been removed.

I checked the CHANGELOG for any mention of this removal, but couldn’t find anything about it. Since these functions are part of the public API, documenting such changes in the CHANGELOG would be very helpful. It would save developers time and assist them in making the necessary adjustments when updating dependencies.

Could you please provide information on the removal of these functions and whether there are alternative methods or replacements available? Additionally, we would appreciate it if future public API changes could be included in the CHANGELOG.

**Comment by sehkone** [comment]
@BLYKIM,

We missed mentioning the above in the CHANGELOG when merging #249. According to our "Rules for Writing a Changelog" in Notion, any change to public methods should be communicated to users in the CHANGELOG.

I understand that `get_node_settings` is no longer used and `get_customer_id_of_review_host` was renamed. Could you update the CHANGELOG accordingly?
