### ISSUE TITLE
GraphQL queries `savedOutliers` and `rankedOutliers` panic with negative pagination parameters

### ISSUE THREAD

**Issue by msk** [aicers/review-web#323]
The GraphQL queries `savedOutliers` and `rankedOutliers` are causing a panic when a web client provides negative values for the `first` or `last` arguments. This is a critical issue that needs to be addressed to prevent unexpected server termination.

## Current Behavior

- When negative values are provided for `first` or `last` arguments in `savedOutliers` and `rankedOutliers` queries, the server panics.
- The panic occurs in the type conversion from `i32` to `usize`.

## Expected Behavior

- The queries should handle negative values gracefully, similar to other pagination functions in the crate.
- Proper error handling should be implemented instead of panicking.

## Detailed Analysis

1. `savedOutliers` In `graphql/outliers.rs`:
   - `OutlierQuery::saved_outliers` calls `load_outliers`, passing `first` and `last` as `Option<i32>`.
   - `load_outliers` attempts to convert these to `Option<usize>` using:
     ```rust
     first.map(|value| usize::try_from(value).expect("valid size")),
     last.map(|value| usize::try_from(value).expect("valid size")),
     ```
   - When `value` is negative, `usize::try_from` returns `Err`, causing a panic.

2. Similarly, `rankedOutliers` in `graphql/outliers.rs`:
   - `OutlierQuery::ranked_outliers` calls `load_ranked_outliers_with_filter`, which panics in:
     ```rust
     first.to_usize().expect("valid size"),
     ```
     and
     ```rust
     last.to_usize().expect("valid size"),
     ```

3. Other queries (e.g., `outliers`) in the same file don't have this issue because they use [`async_graphql::connection::query`](https://docs.rs/async-graphql/latest/async_graphql/types/connection/fn.query.html), which properly handles the conversion from `Option<i32>` to `Option<usize>`.

## Proposed Solution

- Modify `saved_outliers` and `ranked_outliers` to use `async_graphql::connection::query` for parameter handling, consistent with other pagination functions.

## Steps to Reproduce

1. Run review-web's GraphQL playground.
2. Execute a `savedOutliers` or `rankedOutliers` query with a negative value for `first` or `last`.
3. Observe the server panic.

## Environment

- review-web 0.22.0

**Comment by sehkone** [comment]
Thank you for pointing this out.

Initially, I attempted to add code to ensure that both `first` and `last` are positive in both APIs to prevent a panic.

However, I discovered that some APIs don’t call the `load_edges` method, which in turn calls the `validate_and_process_pagination_params` method. This method checks if the pagination parameters are valid and prevents invalid cases, such as when both `before` and `after` are provided simultaneously. The three APIs—`clusters`, `eventList`, and `models`—belong to this group, even though they use `async_graphql::connection::query`.

As a result, we now have three types of APIs that don’t properly validate the parameters. The first type includes those you mentioned, which don’t use `query` and therefore don’t check for negative `first` or `last` values. The second type includes those that don’t call `load_edges` and thus don’t validate the combination of pagination parameters. The third type includes those that don’t use either `query` or `load_edges`; in this group, we currently have just one API, `rankedOutliers`.

In the current design, whenever we add a new API, we need to consider whether it uses `query` and `load_edges` for complete validation, which could easily lead to the coder overlooking this step.

Therefore, I think it would be better if every API independently verifies that the parameters are both valid and meaningful immediately after they are called, by introducing a new method, `validate_pagination_params` to contain all necessary validation, and removing the previous `validate_and_process_pagination_params`, like so:

```rust
    async account_list(...  {
    let _ = validate_pagination_params(after, before, first, last);
        query(
            ...  
    }
```
```rust
    async clusters(... {
       let _ = validate_pagination_params(after, before, first, last);
       ...
    }
```
```rust
     async saved_outliers(... {
        let (first, last) = validate_pagination_params(after, before, first, last);
        load_ranked_outliers_with_filter(ctx, model_id, time, after, before, first, last, filter).await
```

**Comment by msk** [comment]
@sehkone, while I proposed using [`query`](https://docs.rs/async-graphql/latest/async_graphql/types/connection/fn.query.html) for these APIs, I noticed your preference for not doing so in some cases. I would appreciate it if you could share the rationale behind this decision. Are there specific use cases or constraints that `query` cannot address, or are there performance or complexity concerns I might not be aware of? Understanding the reasoning behind not using `query` in these APIs would help me better grasp the trade-offs involved.

**Comment by sehkone** [comment]
> @sehkone, while I proposed using [`query`](https://docs.rs/async-graphql/latest/async_graphql/types/connection/fn.query.html) for these APIs, I noticed your preference for not doing so in some cases. I would appreciate it if you could share the rationale behind this decision. Are there specific use cases or constraints that `query` cannot address, or are there performance or complexity concerns I might not be aware of? Understanding the reasoning behind not using `query` in these APIs would help me better grasp the trade-offs involved.

To be honest, I don't remember why those APIs didn't use `query`. I guess there must have been some misunderstanding. I changed them to use `query`, and they work well now.

On the other hand, I introduced a wrapper for `query` to include validation, allowing the code to remain unchanged except for the path of `query`, which is now `crate::graphql::query`.
