### ISSUE TITLE
`Int` Type Precision Issue in review-web's GraphQL API

### ISSUE THREAD

**Issue by msk** [aicers/review-web#37]
There has been an issue identified concerning the data precision within review-web's GraphQL API related to integer types. At the moment, our GraphQL API employs the `Int` type, a 32-bit signed integer. However, our internal system uses Rust types such as `u32`, `isize`, `usize`, `i64`, and `u64`, which are larger than `i32` and thus, may not be properly converted to `Int`. This mismatch could lead to unintended data truncation or overflow errors when handling large values.

We propose conducting a comprehensive review of all instances in review-web's GraphQL API where the `Int` type is used. This review will evaluate if the `i32` type provides adequate precision for our current needs. If it does, we could refactor the API implementations to use `i32` instead of larger integer types, aligning the internal precision with that of the GraphQL `Int` type.

However, if we find that `i32` does not provide sufficient precision and larger integer types are necessary, it would be advisable to transition to using `StringNumber` provided by async-graphql. This would ensure the necessary precision while preserving compatibility with the GraphQL specification. Please note that this shift would require clients to handle the conversion of `StringNumber` to their respective integer types.

This issue is high priority as it can significantly affect the accuracy and reliability of the data provided to our users. It also presents an opportunity for system optimization and efficient memory usage.

The proposed steps for resolution are:

1. Conduct a comprehensive review of all instances where `Int` is used in review-web's GraphQL API.
2. Determine if the precision provided by `i32` meets the requirements of each use case.
3. If `i32` is adequate, refactor the relevant code to use `i32` rather than larger integer types.
4. If `i32` does not provide the necessary precision, transition to using the `StringNumber` type provided by async-graphql.
5. Perform extensive testing to ensure no precision-related issues emerge after the transition.

**Comment by henry0715-dev** [comment]
- [ ] #259
- [ ] #260
- [ ] #261 
- [ ] #262 
- [ ] #263

**Comment by henry0715-dev** [comment]
aice-web 대응 작업
https://github.com/aicers/aice-web/issues/578

**Comment by sehkone** [comment]
> aice-web 대응 작업 [aicers/aice-web#578](https://github.com/aicers/aice-web/issues/578)

@henry0715-dev 

Since review-web is public and AICE-web is private, this link should be removed according to our rules. Moreover, this issue was specifically aimed at modifying review-web, and since that has been completed, the issue should have been closed.

On the other hand, in AICE-web, we can add this link so that people can recognize it as the related issue.

**Comment by henry0715-dev** [comment]
> > aice-web 대응 작업 [aicers/aice-web#578](https://github.com/aicers/aice-web/issues/578)
> 
> @henry0715-dev
> 
> Since review-web is public and AICE-web is private, this link should be removed according to our rules. Moreover, this issue was specifically aimed at modifying review-web, and since that has been completed, the issue should have been closed.
> 
> On the other hand, in AICE-web, we can add this link so that people can recognize it as the related issue.
@sehkone 
I modified the comment.
Thank you.

**Comment by henry0715-dev** [comment]
It is applied and the issue is closed.
