### ISSUE TITLE
GraphQL을 이용한 Giganto 원격 설정 및 제어 기능 추가

### ISSUE THREAD

**Issue by syncpark** [aicers/review-web#4]
Web UI에서 Giganto의 설정을 수정하면 Giganto에게 수정된 설정 항목을 전송하여 적용하도록 한다.

GraphQL Client 기능 추가:
* Giganto 원격 설정을 위한 GraphQL Client 개발

GraphQL Client를 이용해서 Giganto에 대한 원격 설정 기능을 구현한다.
* retention
  - Node 설정의 Giganto 세부 설정 옵션에 `retention` 추가한다.
  - `retention` 옵션이 수정되면 Giganto에게 적용한다.
* `max_open_files`, `max_mb_of_level_base`: 이들 옵션은 운영중인 Giganto에 영향을 줄 수 있으므로 확인이 필요하다.

Giganto에 대한 원격 제어 기능을 구현한다.
* reboot
* resource usage 가져오기

**Comment by msk** [comment]
Web UI에서 reverse proxy를 통해 giganto의 GraphQL API를 쓸 수 있지 않나요? review-web에서 GraphQL client를 별도로 만들어야 하는 건 왜 그런가요?

**Comment by syncpark** [comment]
지금의 설정 관련 UI와 기능의 구조가 다음과 같은 방식으로 되어있습니다.
* Web UI에서 노드 설정 추가 혹은 수정 => REview-web에서 Validation 및 저장되어있는 기존 설정과 비교 => Hog, Crusher, ... 등에게 명령 전달

그리고 KT TI SAS 프로젝트에서 GraphQL client가 필요한 기능이 추가될 예정입니다.
* REview가 Hog, REconverge 등으로부터 탐지 이벤트 수신 => REview가 Rocks DB에 저장 => REview가 API Server에게 GraphQL 방식으로 탐지이벤트를 전달 => API Server가 Postgres DB에 저장

이들 기능때문에 GraphQL client가 필요합니다. 두 번째 기능은 별도 feature로 분리할 예정이지만요.

**Comment by msk** [comment]
> 지금의 설정 관련 UI와 기능의 구조가 다음과 같은 방식으로 되어있습니다.
> 
> * Web UI에서 노드 설정 추가 혹은 수정 => REview-web에서 Validation 및 저장되어있는 기존 설정과 비교 => Hog, Crusher, ... 등에게 명령 전달

giganto는 기존 Web UI의 노드 설정, 추가, 수정와는 다른 인터페이스(별도 메뉴, 별도 화면 등)를 만들어야 하지 않을까요? 제가 생각하는 이유는 다음 두 가지입니다.

1. giganto는 hog, piglet 등과 달리 REview의 agent가 아닙니다. REview와는 독립적으로 데이터를 저장하는 목적이어서 REview가 없어도 자체 GraphQL API 만으로 쓸 수 있도록 하는 편이 구성 요소간 decoupling 차원에서 바람직합니다.
2. giganto는 클러스터로 구성할 예정이므로 제어 방식 자체가 기존의 "노드" 개념과 맞지 않습니다. giganto의 클러스터 설정, 클러스터별 로드 분산 등을 제어하려면 어차피 별도의 UI가 필요합니다. 지금 굳이 노드 기반 UI에 맞춰 넣으려고 해 봐야 나중에 다 다시 만들게 될 가능성이 큽니다.

@sehkone 현재의 Web UI에 giganto 설정, 제어 관련 부분을 어떻게 넣는 것이 바람직한지 의견주세요.

> 그리고 KT TI SAS 프로젝트에서 GraphQL client가 필요한 기능이 추가될 예정입니다.
> 
> * REview가 Hog, REconverge 등으로부터 탐지 이벤트 수신 => REview가 Rocks DB에 저장 => REview가 API Server에게 GraphQL 방식으로 탐지이벤트를 전달 => API Server가 Postgres DB에 저장
> 
> 이들 기능때문에 GraphQL client가 필요합니다. 두 번째 기능은 별도 feature로 분리할 예정이지만요.

이 부분은 petabi/review-database#25 의 논의와 겹치므로 그쪽에서 계속 얘기하도록 하죠.

**Comment by syncpark** [comment]
`노드` 관련해서 UI에서 관리해야하는 상태 정보는 다음과 같습니다.
1. 리소스 사용율
2. 노드(장비) 연결 상태
3. 노드에서 운용 중인 서비스의 목록과 동작 상태

이 중에서 Giganto가 필수적으로 필요한 상황은 3.번입니다. 노드에서 Giganto가 동작중일 경우 동작 상태 정보가 필요합니다(정상/비정상). UI에서 Giganto 연결 상태 확인을 위한 Query만 구현하면 됩니다.

현재 UI의 경우 서비스들의 제어를 `노드` 관리 화면에서 합니다.
Giganto 관련 설정 항목들은 ...
* graphql address(port)
* ingest address(port)
* publish address(port)
* retention period
* (검토중) max_open_files & max_mb_of_level_base

Giganto가 클러스터로 구성되면 다음 옵션이 추가되어야 합니다.
* cluster address (ip address & port)
* clusters: 클러스터를 구성하는 다른 Giganto의 cluster address와 이름의 목록
* 부하 분산 설정(?)

이 중에서 clusters와 부하 분산 설정은 노드 설정 UI에서 하기에는 까다롭습니다. 이 두가지 옵션만 별도의 Giganto 클러스터 구성 화면에서 설정하도록 하면 되지 않을까 합니다.

**Comment by syncpark** [comment]
만약 Giganto의 특수성(별도 관리)을 허용한다면, 모든 설정항목을 reverse proxy를 사용하든가 아니면 revew-web에서 GraphQL client를 사용하든가 둘 중의 하나만 선택하는게 맞을 듯 합니다.

* reverse proxy를 기반으로 설정한다면 UI가 2 Phase commit 방식으로 review의 RocksDB, Giganto를 설정
* review web에서 GraphQL client 방식을 이용한다면 review web이 기준이되어서 Rocks DB와 Giganto에게 2 phase commit으로 설정

**Comment by sehkone** [comment]
@msk @syncpark 

여러분들의 의견을 취합하여, Giganto는 @msk 의견대로 AICE-web의 노드 관리가 아니라 아닌 다른 메뉴에서 설정 등을 하도록 진행하겠습니다. 다만, AICE-web의 어느 부분에 어떤 메뉴 이름으로 넣을지는 조금 더 생각해 보도록 하겠습니다.
